DROP TABLE USERS CASCADE CONSTRAINTS;

DROP TABLE EXPENSES CASCADE CONSTRAINTS;

purge recyclebin;

-- USERS
CREATE TABLE USERS (
  USER_ID     VARCHAR2(50) PRIMARY KEY,
  USER_NAME   VARCHAR2(50) NOT NULL,
  USER_BIRTH  DATE NOT NULL,
  CREATED_AT  DATE DEFAULT TRUNC(SYSDATE)
);

-- EXPENSES
CREATE TABLE EXPENSES (
  EXP_ID        NUMBER PRIMARY KEY,
  USER_ID       VARCHAR2(50),
  EXP_DATE      DATE,
  EXP_ITEM      VARCHAR2(100),
  EXP_MONEY     NUMBER,
  EXP_TYPE      VARCHAR2(10),
  EXP_CATEGORY  VARCHAR2(50),
  EXP_MEMO      VARCHAR2(200),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

commit;
