DROP TABLE MY_USERS CASCADE CONSTRAINTS;
DROP TABLE EXPENSES CASCADE CONSTRAINTS;

-- 휴지통 비우기
PURGE RECYCLEBIN;

-- MY_USERS 테이블 생성 (회원 관리 테이블)
CREATE TABLE MY_USERS (
  USER_ID     VARCHAR2(50) PRIMARY KEY,
  USER_NAME   VARCHAR2(50) NOT NULL,
  USER_BIRTH  DATE NOT NULL,
  CREATED_AT  DATE DEFAULT TRUNC(SYSDATE)
);

-- EXPENSES 테이블 생성 (수입/지출 내역 테이블)
CREATE TABLE EXPENSES (
  EXP_ID        NUMBER PRIMARY KEY,
  USER_ID       VARCHAR2(50),
  EXP_DATE      DATE,
  EXP_ITEM      VARCHAR2(100),
  EXP_MONEY     NUMBER,
  EXP_TYPE      VARCHAR2(10),
  EXP_CATEGORY  VARCHAR2(50),
  EXP_MEMO      VARCHAR2(200),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES MY_USERS(USER_ID)
);

-- 예시 데이터 
INSERT INTO MY_USERS (USER_ID, USER_NAME, USER_BIRTH)
VALUES ('h1234', '홍길동', TO_DATE('2000-01-01', 'YYYY-MM-DD'));

COMMIT;
